### ISSUE TITLE
Not being dealloced properly

### ISSUE THREAD

**Issue by malhal** [blindingskies/BSFetchedResultsController#4]
I had a crash with it trying to call the delegate after it has been dealloced because the view using the controller was long gone, then I discovered the controller was still alive using Instruments. I believe the problem is the block inside registerNotificationHandlers causes a retain cycle to "self". If I comment out the call to registerNotificationHandlers then the controller is dealloced as normal. I'm using the class in an ARC project but with this file flagged as non-ARC.

**Comment by danthorpe** [comment]
Hi @malhal - this project is really very old. I strongly suggest you consider an alternative as I don't really have time to maintain it. The README contains some strong warnings at the top.

I'm happy to merge any bug fixes you have if you wish to submit a pull request, or you can fork the repository yourself.

Really sorry I can't be of more help.

**Comment by malhal** [comment]
I've not done a pull request yet but will give it a go because I've fixed the problem.

**Comment by danthorpe** [comment]
Well that's great! Creating a pull request is [pretty easy](https://help.github.com/articles/creating-a-pull-request/), I can give you some assistance if you need it?

**Comment by malhal** [comment]
Yes please - I see that before I can do the pull request I need to create a branch, but I can't see how to create a branch.

**Comment by malhal** [comment]
Do I need to fork-and-branch? http://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/

**Comment by danthorpe** [comment]
Okay, well, probably the most easiest is to use GitHub's Mac application, see [here](https://desktop.github.com).

Alternatively a more manual approach is...

1. [Create a fork](https://help.github.com/articles/fork-a-repo/) of this repository to your own GitHub account. Press the Fork button near the top right corner of this page. This will eventually give you access to your own copy of the repository on GitHub. It's be at: https://github.com/malhal/BSFetchedResultsController

2. If you have downloaded the files from this page, you will need to "clone" the files from your fork.
3. *Edit* the files to make and changes you want.
4. *Commit* the changes to your local clone of the repository. This is sort of like saving the files.
5. *Push* the changes up to your fork of the repository.
6. On your fork, it will then prompt you create a pull request to the master branch of *this* repo
7. I can then see your changes, and merge them into my repository (which in this case is referred to as the *upstream* repo).

Hope that helps - not sure how much you know about git...

**Comment by danthorpe** [comment]
You don't actually need to make a branch. You can just make your changes to the master branch. But you do need to fork.

**Comment by malhal** [comment]
Alright that should be it done. Hope I did it right.

**Comment by danthorpe** [comment]
Does it now work? If so, you can close this issue...

**Comment by malhal** [comment]
fixed, and thanks for the pull tutorial
